services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

  app:
    build:
      context: .                         
      dockerfile: app/Dockerfile        
    container_name: rag-bot
    depends_on:
      - ollama
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    environment:
      - OLLAMA_API=http://ollama:11434
      - INDEX_DIR=easemyai_index
    restart: unless-stopped

volumes:
  ollama_models:
